// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpslmayyksnnhyasjaso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhwc2xtYXl5a3Nubmh5YXNqYXNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDg0NDEsImV4cCI6MjA3MTg4NDQ0MX0.lfu-1AFrxg0bGYuDdnpgWCwDfhd62EmLyjqqXOu1EKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});